server:
  port: 8091


coreservice:
  # ЭТО НАДО ПОМЕНЯТЬ
  global-data-dirrectory: "D:/dimka/Desktop/java/personal/projects/ETLServices/coreservice/src/main/resources/"
  folder-path: "vk/messages"
  mq:
    routingkey: coreservice-routing
    exchange: coreservice-exchange
    queue: coreservice-queue
    host: localhost
    port: 5672
    username: guest
    password: guest


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher